typography_spectrum: 0.8712036374490708
color:
  brandStrength: 0.9099636641331017
  lightness: 0.780349753331393
  saturation: 0.9559973026625812
  rhythmicContrast: 0.7802428386639804
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
layout_spectrum: 0.5955512102227658
author:
  name: All English Hyper-Immersion Program
  email: ericupsidebrown@gmail.com
  url: 'http://allenglish.com'
name: All English Blog
title: All English Blog
description: Helping the World Connect with English
